### ISSUE TITLE
Please give me advice how get better accuracy

### ISSUE THREAD

**Issue by globalik** [drscotthawley/panotti#36]
Hi i using your CNN and work for me everything very good.  I using your CNN  for sound recognizing from dataset ESC 50 https://github.com/karoldvl/ESC-50. I get choice 10 class from this dataset it is 400 sound file (40 sound on class). I using for training 80% data (320 sound file) and for testing 20% data (80 sound file). My accuracyy is approximately 57%. How i can get better accuracy?

I run training with these setting: python train_network.py -- batch_size 30 --epochs 300

My accuracy after this training is 57% but i need more ideal is ≈75%

Please help thanks for reply.

**Comment by drscotthawley** [comment]
Hi @globalik , looking at that ESC 50 page, it looks like many of the more successful submissions used data augmentation. 

 Panotti has a utils/augment_data.py that you should probably try; it's mentioned on the README.  
I confess I haven't used it in a while so let me know if something's broken.  You could increase the size of the dataset by a factor of two (N=1 more augmentations) or five (N=4).  

That said, I don't claim the Panotti model to be SOTA; it is fast, and the model is simple enough for someone like me to understand, but more sophisticated or more carefully-tuned model would definitely score higher.

**Comment by drscotthawley** [comment]
You're a Windows user and you're trying to use Unix-style forward slashes to specify filenames? That seems to be a serious usage error.   
As noted in the README: "Windows users, I have no experience to offer you". 

The error you're getting is because it can't read one of your audio files.  Either because you're not specifying filenames correctly on your system, or the file is corrupted, or there's a problem with your librosa or audioread installation.  Check here: https://github.com/librosa/librosa/issues/219

**Comment by globalik** [comment]
Files with dataset ESC 50 are preprocessing correctly but for augemented files who are preprocessing show No Backends error. I Don't know why.

**Comment by globalik** [comment]
I now edit augment_audio.py and now is fully automatic. Thanks for help 🥇

**Comment by ngragaei** [comment]
Many thanks for u :) @globalik
