### ISSUE TITLE
AttributeError: 'MultiGPUModelCheckpoint' object has no attribute 'on_train_batch_begin'

### ISSUE THREAD

**Issue by ngragaei** [drscotthawley/panotti#56]
How to solve this error? 
Thanks in advance!

**Comment by drscotthawley** [comment]
So, I think is a Keras *version* problem.  The (older) version of Keras that Panotti was written for didn't require this. 

 The requirements.txt file reads `Keras>=2.1.3` but really, since they changed things in the newer Keras, bets are off.  I should change  that `>=` to a `==`.  

Until I get around to updating Panotti for newer Keras, my temporary suggestion would be to manually add a `on_train_batch_begin()` method into the MultiGPUModelCheckpoint code, one that does absolutely nothing and immediately returns.  

Or, you could try downgrading to Keras 2.1.3.

**Comment by ngragaei** [comment]
Many thanks :)
